version: '3.1'
services:
  db:
    image: mysql
    container_name: dev-spring-boot
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - github-data:/var/lib/dev-spring-boot

volumes:
  github-data: